Paper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.news_list, name='news_list'),
    path('<int:news_id>/', views.news_detail, name='news_detail'),
    path('search/', views.news_search, name='news_search'),
    path('add/', views.news_create, name='news_create'),
    path('<int:news_id>/edit/', views.news_edit, name='news_edit'),
    path('<int:news_id>/delete/', views.news_delete, name='news_delete'),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class News(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        app_label = 'news'
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('news:news_detail', args=[str(self.id)])


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

    def update_rating(self):
        # Суммарный рейтинг каждой статьи умножается на 3 и суммируется
        post_rating = sum(post.rating * 3 for post in self.post_set.all())

        # Суммарный рейтинг всех комментариев автора
        comment_rating = sum(comment.rating for comment in Comment.objects.filter(user=self.user))

        # Суммарный рейтинг всех комментариев к статьям автора
        post_comment_rating = sum(comment.rating for post in self.post_set.all() for comment in post.comment_set.all())

        # Обновление рейтинга автора
        self.rating = post_rating + comment_rating + post_comment_rating
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    POST_TYPES = (
        ('article', 'Статья'),
        ('news', 'Новость'),
    )
    post_type = models.CharField(max_length=10, choices=POST_TYPES)
    created_at = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=255)
    content = models.TextField()
    rating = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.content[0:123] + '...'

class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return f"Комментарий от {self.user.username} к {self.post.title}"

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

news/forms.py
from django import forms
from .models import News

class NewsSearchForm(forms.Form):
    search_date = forms.DateField(required=False, label='Дата (ГГГГ-ММ-ДД)')
    search_title = forms.CharField(required=False, max_length=200, label='Название')
    search_author = forms.CharField(required=False, max_length=100, label='Автор')

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'content']  # Здесь укажите поля, которые вы хотите редактировать

news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import News
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .forms import NewsForm

def news_list(request):
    news_list = News.objects.all()
    paginator = Paginator(news_list, 10)  # Разбиваем новости на страницы, по 10 новостей на каждой
    page = request.GET.get('page')
    news = paginator.get_page(page)
    return render(request, 'news/news_list.html', {'news': news})


def news_detail(request, news_id):
    news = get_object_or_404(News, pk=news_id)
    return render(request, 'news/news_detail.html', {'news': news})


def news_search(request):
    # Получение параметров поиска из GET-запроса
    search_date = request.GET.get('date')
    search_title = request.GET.get('title')
    search_author = request.GET.get('author')

    # Фильтрация новостей на основе параметров поиска
    news_list = News.objects.all()

    if search_date:
        news_list = news_list.filter(pub_date__gte=search_date)

    if search_title:
        news_list = news_list.filter(title__icontains=search_title)

    if search_author:
        news_list = news_list.filter(author__username=search_author)

    # Реализация постраничного вывода
    paginator = Paginator(news_list, 10)
    page = request.GET.get('page')
    try:
        news = paginator.page(page)
    except PageNotAnInteger:
        news = paginator.page(1)
    except EmptyPage:
        news = paginator.page(paginator.num_pages)

    return render(request, 'news/news_search.html', {'news': news})


def news_create(request):
    if request.method == 'POST':
        form = NewsForm(request.POST)
        if form.is_valid():
            news = form.save()
            return redirect('news:news_detail', news.id)
    else:
        form = NewsForm()
    return render(request, 'news/news_form.html', {'form': form})

def news_edit(request, news_id):
    news = get_object_or_404(News, id=news_id)
    if request.method == 'POST':
        form = NewsForm(request.POST, instance=news)
        if form.is_valid():
            news = form.save()
            return redirect('news:news_detail', news.id)
    else:
        form = NewsForm(instance=news)
    return render(request, 'news/news_form.html', {'form': form, 'news': news})

def news_delete(request, news_id):
    news = get_object_or_404(News, id=news_id)
    if request.method == 'POST':
        news.delete()
        return redirect('news:news_list')
    return render(request, 'news/news_confirm_delete.html', {'news': news})

templates/news/base.html
<!--{% load static %}-->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<title>
{% block title %}
{% endblock title %}
</title>
</head>
<body>
{% include 'news/parts/header.html' %}
<div class="container">
 {% block content %}
 {% endblock content %}
</div>

{% include 'news/parts/footer.html' %}
</body>
</html>

templates/news/news_confirm_delete.html
{% extends 'news/base.html' %}
{% load filters %}

{% block content %}
  <h1>Вы уверены, что хотите удалить новость "{{ news.title }}"?</h1>
  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
  </form>
  <a href="{% url 'news:news_list' %}">Отмена</a>
{% endblock %}

templates/news/news_detail.html
{% extends 'news/base.html' %}
{% load filters %}

{% block content %}
<h1>Новость</h1>
<h2>{{ news.title }}</h2>
<p>Автор: {{ author_name }}</p>
<p>Дата: {{ news.pub_date|date:"d-m-Y H:i" }}</p>
<p>{{ news.content|censor }}</p>
{% endblock %}

templates/news/news_form.html
{% extends 'news/base.html' %}
{% load filters %}

{% block content %}
  <h1>{% if news %}Редактировать новость{% else %}Создать новость{% endif %}</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% if news %}Сохранить{% else %}Создать{% endif %}">
  </form>
{% endblock %}

templates/news/news_list.html
{% extends 'news/base.html' %}
{% load filters %}

{% block content %}
  <h1>Список новостей</h1>

  <ul>
    {% for news in news %}
      <li>
        <a href="{% url 'news:news_detail' news.id %}">{{ news.title|censor }}</a>
        ({{ news.pub_date|date:"d-m-Y H:i" }})
        {{ news.content|censor|slice:":50" }}...
      </li>
    {% endfor %}
  </ul>

  <div class="pagination">
    <span class="step-links">
      {% if news.has_previous %}
        <a href="?page=1">&laquo; первая</a>
        <a href="?page={{ news.previous_page_number }}">предыдущая</a>
      {% endif %}

      <span class="current-page">
        Страница {{ news.number }} из {{ news.paginator.num_pages }}.
      </span>

      {% if news.has_next %}
        <a href="?page={{ news.next_page_number }}">следующая</a>
        <a href="?page={{ news.paginator.num_pages }}">последняя &raquo;</a>
      {% endif %}
    </span>
  </div>
</div>
{% endblock %}

templates/news/news_search.html
{% extends 'news/base.html' %}
{% load filters %}

{% block content %}
<h1>Поиск новостей</h1>
<form method="get" action="{% url 'news:news_search' %}">
    <input type="date" name="date" placeholder="Позже даты (гггг-мм-дд)">
    <input type="text" name="title" placeholder="По названию">
    <input type="text" name="author" placeholder="По автору">
    <input type="submit" value="Искать">
</form>
<ul>
    {% for item in news %}
        <li>
            <a href="{% url 'news:news_detail' item.id %}">{{ item.title }}</a>
            ({{ item.pub_date|date:"d-m-Y H:i" }})
            {{ item.content|slice:":50" }}...
        </li>
    {% endfor %}
</ul>
<div class="pagination">
    <span class="step-links">
        {% if news.has_previous %}
            <a href="?page=1">&laquo; первая</a>
            <a href="?page={{ news.previous_page_number }}">предыдущая</a>
        {% endif %}
        <span class="current-page">
            Страница {{ news.number }} из {{ news.paginator.num_pages }}.
        </span>
        {% if news.has_next %}
            <a href="?page={{ news.next_page_number }}">следующая</a>
            <a href="?page={{ news.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/news/parts/footer.html
<!DOCTYPE html>
<footer class="footer mt-auto py-3 bg-light">
 <div class="container">
   <span class="text-muted">Place sticky footer content here.</span>
 </div>
</footer>

templates/news/parts/header.html
<!DOCTYPE html>
<header class="p-3 text-bg-dark">
 <div class="container">
   <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
     <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
       <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
     </a>

     <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
       <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
       <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
       <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
       <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
       <li><a href="#" class="nav-link px-2 text-white">About</a></li>
     </ul>

     <div class="text-end">
       <button type="button" class="btn btn-outline-light me-2">Login</button>
       <button type="button" class="btn btn-warning">Sign-up</button>
     </div>
   </div>
 </div>
</header>